# Generated by Django 3.1.5 on 2021-01-21 11:01

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POICategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('name', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='maps.POICategory')),
            ],
        ),
    ]
