# Generated by Django 3.1.5 on 2021-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name_plural': 'POI'},
        ),
        migrations.AlterModelOptions(
            name='poicategory',
            options={'verbose_name_plural': 'POI Categories'},
        ),
        migrations.AlterField(
            model_name='poi',
            name='geometry',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
